services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mini-banco-central
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: