### Criar instituição
POST http://localhost:3000/instituicoes
Content-Type: application/json

{
  "name": "Banco do Brasil"
}

###

POST http://localhost:3000/instituicoes
Content-Type: application/json

{
  "name": "Itaú"
}

###

POST http://localhost:3000/instituicoes
Content-Type: application/json

{
  "name": "Nubank"
}