### Criar usuário
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "name": "Stela Oliveira",
  "email": "stela@email.com"
}

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "name": "Maria Souza",
  "email": "maria@email.com"
}